version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production # variavel de ambiente para o Docker file
    environment:
      - NODE_ENV=production
    command: node ./server.js